language: python

python:
    - "3.5"

branches:
  only:
    - master

sudo: false

install:
  - pip install pip
  - pip install --upgrade pip
  - pip install packaging
  - pip install setuptools
  - pip install six
  - pip install -r docs/requirements.txt
  - conda config --set always_yes yes --set changeps1 no
  - conda create -c https://conda.anaconda.org/rdkit -n my-rdkit-env rdkit
  - source activate my-rdkit-env
  - conda install pandas
  - pip install matplotlib
  - pip install nolearn
  - conda install boto
  - conda install --channel https://conda.anaconda.org/openbabel openbabel
  - curl -O https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pychem/pychem-1.0.tar.gz
  - tar -xvzf pychem-1.0.tar.gz
  - curl -O https://raw.githubusercontent.com/dacb/pychem_python3_patchset/master/pychem_python3.patch
  - patch -p0 < pychem_python3.patch
  - cd pychem-1.0
  - python setup.py install
  - cd ..
  - git clone https://github.com/rahulavadhoot/USP-inhibition
  - pip install coveralls
  - pip install nose
  - cd USP-inhibition
  - cd scripts
  - python driver.py install

script:
  - nosetests --with-doctest --with-coverage

after_success:
    - coveralls
