language: python

python:
    - "2.7"

branches:
  only:
    - master

sudo: false

install:
  - pip install pip
  - pip install --upgrade pip
  - pip install packaging
  - pip install setuptools
  - pip install six
  - curl -O https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -c https://conda.anaconda.org/rdkit -n my-rdkit-env rdkit
  - source activate my-rdkit-env
  - conda install --yes --channel https://conda.anaconda.org/openbabel openbabel
  - curl -O https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pychem/pychem-1.0.tar.gz
  - tar -xvzf pychem-1.0.tar.gz
  - curl -O https://raw.githubusercontent.com/dacb/pychem_python3_patchset/master/pychem_python3.patch
  - patch -p0 < pychem_python3.patch
  - cd pychem-1.0
  - python setup.py install
  - cd ..
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - git clone https://github.com/rahulavadhoot/USP-inhibition
  - cd USP-inhibition
  - cd scripts
  - python driver.py install

script:
  - nosetests --with-doctest --with-coverage

after_success:
    - coveralls
