language: python

python:
    - "2.7"

branches:
  only:
    - master

sudo: false

install:
  - pip install pip
  - pip install --upgrade pip
  - pip install packaging
  - pip install setuptools
  - pip install six
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - python driver.py install

script:
  - nosetests --with-doctest --with-coverage

after_success:
    - coveralls
